### ISSUE TITLE
Unlock with Apple Watch

### ISSUE THREAD

**Issue by frbuccoliero** [theilliteratemessiah/Dell-XPS-9570-Big-Sur#2]
Hi, i have a XPS9570 but i followed jaromeyer EFI, i was looking at your repo and saw you selected "Unlock with Apple Watch" as working, to me it's not perfectly working, it disables automatically after reboot or back from sleep. Is the same for you or does it work as a real mac?
Thanks

**Comment by theilliteratemessiah** [comment]
Apologies for a tardy response. Unlock with Apple Watch works perfectly with this configuration, having been tested with a number of rebuilds and Apple Watch 1 and 6.

Hope that helps.

**Comment by frbuccoliero** [comment]
What wifi/bt card do you use?

**Comment by theilliteratemessiah** [comment]
I am using the BCM94360NG  card, bought off eBay for about £40.

**Comment by frbuccoliero** [comment]
Mhh, i have the DW1820A , bit cheaper, maybe it's that. Thanks anyway!
